### ISSUE TITLE
[Bug]  运行报错 Failed to resolve 'pan.quark.cn'

### ISSUE THREAD

**Issue by gujiwuqing** [Cp0204/quark-auto-save#10]
### What happened

⚙️ 读取到 QUARK_COOKIE 环境变量，仅签到领空间。如需执行转存，请删除该环境变量后配置 quark_config.json 文件
===============签到任务===============
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f3f1a020e50>: Failed to resolve 'pan.quark.cn' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pan.quark.cn', port=443): Max retries exceeded with url: /account/info?fr=pc&platform=pc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3f1a020e50>: Failed to resolve 'pan.quark.cn' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 913, in <module>
    main()
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 883, in main
    do_sign(account)
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 758, in do_sign
    if not verify_account(account):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 747, in verify_account
    account_info = account.init()
                   ^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 123, in init
    account_info = self.get_account_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 138, in get_account_info
    response = requests.request(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pan.quark.cn', port=443): Max retries exceeded with url: /account/info?fr=pc&platform=pc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3f1a020e50>: Failed to resolve 'pan.quark.cn' ([Errno -3] Try again)"))

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Qinglong

**Comment by Cp0204** [comment]
给容器设自定义DNS，已知腾讯云默认的DNS解析不了夸克的域名
