### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by huoshenw** [Cp0204/quark-auto-save#26]
### What happened

青龙报错

### Config & Log

⚙️ 读取到 QUARK_COOKIE 环境变量，仅签到领空间。如需执行转存，请删除该环境变量后配置 quark_config.json 文件
===============签到任务===============
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 907, in <module>
    main()
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 877, in main
    do_sign(account)
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 751, in do_sign
    if not verify_account(account):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 740, in verify_account
    account_info = account.init()
                   ^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 122, in init
    account_info = self.get_account_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 137, in get_account_info
    response = requests.request(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 397, in request
    self.putheader(header, value)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 311, in putheader
    super().putheader(header, *values)
  File "/usr/local/lib/python3.11/http/client.py", line 1276, in putheader
    values[i] = one_value.encode('latin-1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

### Operating environment

Qinglong

**Comment by Cp0204** [comment]
網絡環境問題
