### ISSUE TITLE
[Bug] alist_strm_gen不支持的驱动没有容错处理报错

### ISSUE THREAD

**Issue by BigApple96** [Cp0204/quark-auto-save#43]
### What happened

使用alist_strm_gen的时候quarkTV驱动在storage_id出填写id出现报错

### Config & Log

🧩 载入媒体库模块
Alist刷新: AList v3.40.0
Alist-Strm生成: QuarkTV[/quarkTV]
Alist刷新: 不支持[QuarkTV]驱动 ❌
Traceback (most recent call last):
  File "/app/./quark_auto_save.py", line 920, in 
    main()
    ~~~~^^
  File "/app/./quark_auto_save.py", line 898, in main
    do_save(accounts[0], [tasklist[task_index]])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 781, in do_save
    media_servers = load_media_servers(CONFIG_DATA.get("media_servers", {}))
  File "/app/./quark_auto_save.py", line 715, in load_media_servers
    media_servers[module_name] = ServerClass(**server_config)
                                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/app/media_servers/alist_strm_gen.py", line 41, in __init__
    success, result = self.storage_id_to_path(self.storage_id)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object


### Operating environment

Qinglong

### Environment version

0.3.8.1

**Comment by Cp0204** [comment]
谢谢反馈，已解决，将在 `v0.3.9` 修复
