### ISSUE TITLE
运行脚本错误提示

### ISSUE THREAD

**Issue by wlqb2001** [Cp0204/quark-auto-save#8]
### What happened

运行错误提示

### Config & Log

Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### Operating environment

Qinglong

**Comment by Cp0204** [comment]
青龙-依赖管理-Python3，右上角，创建依赖，名称：requests

**Comment by wlqb2001** [comment]
安装后运行提示
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.swap.py", line 901, in <module>
    main()
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.swap.py", line 871, in main
    do_sign(account)
  File "/ql/data/scripts/Cp0204_quark-auto-save/quark_auto_save.swap.py", line 762, in do_sign
    CONFIG_DATA.get("push_config").get("QUARK_SIGN_NOTIFY") == False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Cp0204** [comment]
> push_config

重新运行一下拉库
